language: node_js
node_js:
  - "stable"
git:
  depth: 5
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: redux-sink
      before_install:
        - npm install typescript
        - npm run install
        - npm run build
      script: npm run test