import { uniqueId } from '../uniqueId';
import { Function, ActionFunction } from '../types';

/**
 * create action based on action function and action type
 * action.toString() will return the action type
 * @param func action function creates the payload, by default will use payload directly
 * @param type redux action tyep, by default will generated by random uniqueId
 */
export function createAction(func?: Function, type?: string) {
  const actionType = type || uniqueId();
  const actionFunction = func || ((payload) => payload);
  
  const action = function(...args) {
    return ({
      type: actionType, 
      payload: actionFunction(...args)
    })
  };
  action.toString = () => actionType;
  return action as ActionFunction;
}